<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-KursuTV.Worker-bee4307c-4b2b-4293-9dde-e7602b8c8b1b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!-- RabbitMQ mesajlaşma -->
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <!-- Host -->
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
    <!-- Redis cache invalidation -->
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
    <!-- WebP görsel dönüşümü -->
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KursuTV.Business\KursuTV.Business.csproj" />
    <ProjectReference Include="..\KursuTV.Data\KursuTV.Data.csproj" />
  </ItemGroup>

</Project>
